# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mirko/Dev/qgroundcontrol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mirko/Dev/qgroundcontrol

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mirko/Dev/qgroundcontrol/CMakeFiles /home/mirko/Dev/qgroundcontrol//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mirko/Dev/qgroundcontrol/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QGroundControl

# Build rule for target.
QGroundControl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QGroundControl
.PHONY : QGroundControl

# fast build rule for target.
QGroundControl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/build
.PHONY : QGroundControl/fast

#=============================================================================
# Target rules for targets named QGroundControl_autogen

# Build rule for target.
QGroundControl_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QGroundControl_autogen
.PHONY : QGroundControl_autogen

# fast build rule for target.
QGroundControl_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl_autogen.dir/build.make CMakeFiles/QGroundControl_autogen.dir/build
.PHONY : QGroundControl_autogen/fast

#=============================================================================
# Target rules for targets named libevents_parser

# Build rule for target.
libevents_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libevents_parser
.PHONY : libevents_parser

# fast build rule for target.
libevents_parser/fast:
	$(MAKE) $(MAKESILENT) -f libs/libevents/CMakeFiles/libevents_parser.dir/build.make libs/libevents/CMakeFiles/libevents_parser.dir/build
.PHONY : libevents_parser/fast

#=============================================================================
# Target rules for targets named libevents_generated

# Build rule for target.
libevents_generated: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libevents_generated
.PHONY : libevents_generated

# fast build rule for target.
libevents_generated/fast:
	$(MAKE) $(MAKESILENT) -f libs/libevents/CMakeFiles/libevents_generated.dir/build.make libs/libevents/CMakeFiles/libevents_generated.dir/build
.PHONY : libevents_generated/fast

#=============================================================================
# Target rules for targets named libevents_parser_autogen

# Build rule for target.
libevents_parser_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libevents_parser_autogen
.PHONY : libevents_parser_autogen

# fast build rule for target.
libevents_parser_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/libevents/CMakeFiles/libevents_parser_autogen.dir/build.make libs/libevents/CMakeFiles/libevents_parser_autogen.dir/build
.PHONY : libevents_parser_autogen/fast

#=============================================================================
# Target rules for targets named libevents_generated_autogen

# Build rule for target.
libevents_generated_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libevents_generated_autogen
.PHONY : libevents_generated_autogen

# fast build rule for target.
libevents_generated_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/libevents/CMakeFiles/libevents_generated_autogen.dir/build.make libs/libevents/CMakeFiles/libevents_generated_autogen.dir/build
.PHONY : libevents_generated_autogen/fast

#=============================================================================
# Target rules for targets named shp

# Build rule for target.
shp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shp
.PHONY : shp

# fast build rule for target.
shp/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shp.dir/build.make libs/shapelib/CMakeFiles/shp.dir/build
.PHONY : shp/fast

#=============================================================================
# Target rules for targets named dbfcreate

# Build rule for target.
dbfcreate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbfcreate
.PHONY : dbfcreate

# fast build rule for target.
dbfcreate/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/dbfcreate.dir/build.make libs/shapelib/CMakeFiles/dbfcreate.dir/build
.PHONY : dbfcreate/fast

#=============================================================================
# Target rules for targets named dbfdump

# Build rule for target.
dbfdump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbfdump
.PHONY : dbfdump

# fast build rule for target.
dbfdump/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/dbfdump.dir/build.make libs/shapelib/CMakeFiles/dbfdump.dir/build
.PHONY : dbfdump/fast

#=============================================================================
# Target rules for targets named shpadd

# Build rule for target.
shpadd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shpadd
.PHONY : shpadd

# fast build rule for target.
shpadd/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shpadd.dir/build.make libs/shapelib/CMakeFiles/shpadd.dir/build
.PHONY : shpadd/fast

#=============================================================================
# Target rules for targets named shpdump

# Build rule for target.
shpdump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shpdump
.PHONY : shpdump

# fast build rule for target.
shpdump/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shpdump.dir/build.make libs/shapelib/CMakeFiles/shpdump.dir/build
.PHONY : shpdump/fast

#=============================================================================
# Target rules for targets named shptreedump

# Build rule for target.
shptreedump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shptreedump
.PHONY : shptreedump

# fast build rule for target.
shptreedump/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shptreedump.dir/build.make libs/shapelib/CMakeFiles/shptreedump.dir/build
.PHONY : shptreedump/fast

#=============================================================================
# Target rules for targets named dbfadd

# Build rule for target.
dbfadd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbfadd
.PHONY : dbfadd

# fast build rule for target.
dbfadd/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/dbfadd.dir/build.make libs/shapelib/CMakeFiles/dbfadd.dir/build
.PHONY : dbfadd/fast

#=============================================================================
# Target rules for targets named shprewind

# Build rule for target.
shprewind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shprewind
.PHONY : shprewind

# fast build rule for target.
shprewind/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shprewind.dir/build.make libs/shapelib/CMakeFiles/shprewind.dir/build
.PHONY : shprewind/fast

#=============================================================================
# Target rules for targets named shpcreate

# Build rule for target.
shpcreate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shpcreate
.PHONY : shpcreate

# fast build rule for target.
shpcreate/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shpcreate.dir/build.make libs/shapelib/CMakeFiles/shpcreate.dir/build
.PHONY : shpcreate/fast

#=============================================================================
# Target rules for targets named shp_autogen

# Build rule for target.
shp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shp_autogen
.PHONY : shp_autogen

# fast build rule for target.
shp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shp_autogen.dir/build.make libs/shapelib/CMakeFiles/shp_autogen.dir/build
.PHONY : shp_autogen/fast

#=============================================================================
# Target rules for targets named dbfcreate_autogen

# Build rule for target.
dbfcreate_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbfcreate_autogen
.PHONY : dbfcreate_autogen

# fast build rule for target.
dbfcreate_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/dbfcreate_autogen.dir/build.make libs/shapelib/CMakeFiles/dbfcreate_autogen.dir/build
.PHONY : dbfcreate_autogen/fast

#=============================================================================
# Target rules for targets named dbfdump_autogen

# Build rule for target.
dbfdump_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbfdump_autogen
.PHONY : dbfdump_autogen

# fast build rule for target.
dbfdump_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/dbfdump_autogen.dir/build.make libs/shapelib/CMakeFiles/dbfdump_autogen.dir/build
.PHONY : dbfdump_autogen/fast

#=============================================================================
# Target rules for targets named shpadd_autogen

# Build rule for target.
shpadd_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shpadd_autogen
.PHONY : shpadd_autogen

# fast build rule for target.
shpadd_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shpadd_autogen.dir/build.make libs/shapelib/CMakeFiles/shpadd_autogen.dir/build
.PHONY : shpadd_autogen/fast

#=============================================================================
# Target rules for targets named shpdump_autogen

# Build rule for target.
shpdump_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shpdump_autogen
.PHONY : shpdump_autogen

# fast build rule for target.
shpdump_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shpdump_autogen.dir/build.make libs/shapelib/CMakeFiles/shpdump_autogen.dir/build
.PHONY : shpdump_autogen/fast

#=============================================================================
# Target rules for targets named shptreedump_autogen

# Build rule for target.
shptreedump_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shptreedump_autogen
.PHONY : shptreedump_autogen

# fast build rule for target.
shptreedump_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shptreedump_autogen.dir/build.make libs/shapelib/CMakeFiles/shptreedump_autogen.dir/build
.PHONY : shptreedump_autogen/fast

#=============================================================================
# Target rules for targets named dbfadd_autogen

# Build rule for target.
dbfadd_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbfadd_autogen
.PHONY : dbfadd_autogen

# fast build rule for target.
dbfadd_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/dbfadd_autogen.dir/build.make libs/shapelib/CMakeFiles/dbfadd_autogen.dir/build
.PHONY : dbfadd_autogen/fast

#=============================================================================
# Target rules for targets named shprewind_autogen

# Build rule for target.
shprewind_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shprewind_autogen
.PHONY : shprewind_autogen

# fast build rule for target.
shprewind_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shprewind_autogen.dir/build.make libs/shapelib/CMakeFiles/shprewind_autogen.dir/build
.PHONY : shprewind_autogen/fast

#=============================================================================
# Target rules for targets named shpcreate_autogen

# Build rule for target.
shpcreate_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shpcreate_autogen
.PHONY : shpcreate_autogen

# fast build rule for target.
shpcreate_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/shapelib/CMakeFiles/shpcreate_autogen.dir/build.make libs/shapelib/CMakeFiles/shpcreate_autogen.dir/build
.PHONY : shpcreate_autogen/fast

#=============================================================================
# Target rules for targets named qmlglsink

# Build rule for target.
qmlglsink: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qmlglsink
.PHONY : qmlglsink

# fast build rule for target.
qmlglsink/fast:
	$(MAKE) $(MAKESILENT) -f libs/qmlglsink/CMakeFiles/qmlglsink.dir/build.make libs/qmlglsink/CMakeFiles/qmlglsink.dir/build
.PHONY : qmlglsink/fast

#=============================================================================
# Target rules for targets named qmlglsink_autogen

# Build rule for target.
qmlglsink_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qmlglsink_autogen
.PHONY : qmlglsink_autogen

# fast build rule for target.
qmlglsink_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/qmlglsink/CMakeFiles/qmlglsink_autogen.dir/build.make libs/qmlglsink/CMakeFiles/qmlglsink_autogen.dir/build
.PHONY : qmlglsink_autogen/fast

#=============================================================================
# Target rules for targets named qgc

# Build rule for target.
qgc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qgc
.PHONY : qgc

# fast build rule for target.
qgc/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/qgc.dir/build.make src/CMakeFiles/qgc.dir/build
.PHONY : qgc/fast

#=============================================================================
# Target rules for targets named qgc_autogen

# Build rule for target.
qgc_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qgc_autogen
.PHONY : qgc_autogen

# fast build rule for target.
qgc_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/qgc_autogen.dir/build.make src/CMakeFiles/qgc_autogen.dir/build
.PHONY : qgc_autogen/fast

#=============================================================================
# Target rules for targets named uiQml

# Build rule for target.
uiQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uiQml
.PHONY : uiQml

# fast build rule for target.
uiQml/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/uiQml.dir/build.make src/ui/CMakeFiles/uiQml.dir/build
.PHONY : uiQml/fast

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui.dir/build.make src/ui/CMakeFiles/ui.dir/build
.PHONY : ui/fast

#=============================================================================
# Target rules for targets named ui_autogen

# Build rule for target.
ui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_autogen
.PHONY : ui_autogen

# fast build rule for target.
ui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui_autogen.dir/build.make src/ui/CMakeFiles/ui_autogen.dir/build
.PHONY : ui_autogen/fast

#=============================================================================
# Target rules for targets named UiPreferencesQml

# Build rule for target.
UiPreferencesQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UiPreferencesQml
.PHONY : UiPreferencesQml

# fast build rule for target.
UiPreferencesQml/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/preferences/CMakeFiles/UiPreferencesQml.dir/build.make src/ui/preferences/CMakeFiles/UiPreferencesQml.dir/build
.PHONY : UiPreferencesQml/fast

#=============================================================================
# Target rules for targets named UiToolbarQml

# Build rule for target.
UiToolbarQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UiToolbarQml
.PHONY : UiToolbarQml

# fast build rule for target.
UiToolbarQml/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/toolbar/CMakeFiles/UiToolbarQml.dir/build.make src/ui/toolbar/CMakeFiles/UiToolbarQml.dir/build
.PHONY : UiToolbarQml/fast

#=============================================================================
# Target rules for targets named ADSB

# Build rule for target.
ADSB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ADSB
.PHONY : ADSB

# fast build rule for target.
ADSB/fast:
	$(MAKE) $(MAKESILENT) -f src/ADSB/CMakeFiles/ADSB.dir/build.make src/ADSB/CMakeFiles/ADSB.dir/build
.PHONY : ADSB/fast

#=============================================================================
# Target rules for targets named ADSB_autogen

# Build rule for target.
ADSB_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ADSB_autogen
.PHONY : ADSB_autogen

# fast build rule for target.
ADSB_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/ADSB/CMakeFiles/ADSB_autogen.dir/build.make src/ADSB/CMakeFiles/ADSB_autogen.dir/build
.PHONY : ADSB_autogen/fast

#=============================================================================
# Target rules for targets named Airmap

# Build rule for target.
Airmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Airmap
.PHONY : Airmap

# fast build rule for target.
Airmap/fast:
	$(MAKE) $(MAKESILENT) -f src/Airmap/CMakeFiles/Airmap.dir/build.make src/Airmap/CMakeFiles/Airmap.dir/build
.PHONY : Airmap/fast

#=============================================================================
# Target rules for targets named Airmap_autogen

# Build rule for target.
Airmap_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Airmap_autogen
.PHONY : Airmap_autogen

# fast build rule for target.
Airmap_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Airmap/CMakeFiles/Airmap_autogen.dir/build.make src/Airmap/CMakeFiles/Airmap_autogen.dir/build
.PHONY : Airmap_autogen/fast

#=============================================================================
# Target rules for targets named AnalyzeViewQml

# Build rule for target.
AnalyzeViewQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AnalyzeViewQml
.PHONY : AnalyzeViewQml

# fast build rule for target.
AnalyzeViewQml/fast:
	$(MAKE) $(MAKESILENT) -f src/AnalyzeView/CMakeFiles/AnalyzeViewQml.dir/build.make src/AnalyzeView/CMakeFiles/AnalyzeViewQml.dir/build
.PHONY : AnalyzeViewQml/fast

#=============================================================================
# Target rules for targets named AnalyzeView

# Build rule for target.
AnalyzeView: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AnalyzeView
.PHONY : AnalyzeView

# fast build rule for target.
AnalyzeView/fast:
	$(MAKE) $(MAKESILENT) -f src/AnalyzeView/CMakeFiles/AnalyzeView.dir/build.make src/AnalyzeView/CMakeFiles/AnalyzeView.dir/build
.PHONY : AnalyzeView/fast

#=============================================================================
# Target rules for targets named AnalyzeView_autogen

# Build rule for target.
AnalyzeView_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AnalyzeView_autogen
.PHONY : AnalyzeView_autogen

# fast build rule for target.
AnalyzeView_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/AnalyzeView/CMakeFiles/AnalyzeView_autogen.dir/build.make src/AnalyzeView/CMakeFiles/AnalyzeView_autogen.dir/build
.PHONY : AnalyzeView_autogen/fast

#=============================================================================
# Target rules for targets named api

# Build rule for target.
api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 api
.PHONY : api

# fast build rule for target.
api/fast:
	$(MAKE) $(MAKESILENT) -f src/api/CMakeFiles/api.dir/build.make src/api/CMakeFiles/api.dir/build
.PHONY : api/fast

#=============================================================================
# Target rules for targets named api_autogen

# Build rule for target.
api_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 api_autogen
.PHONY : api_autogen

# fast build rule for target.
api_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/api/CMakeFiles/api_autogen.dir/build.make src/api/CMakeFiles/api_autogen.dir/build
.PHONY : api_autogen/fast

#=============================================================================
# Target rules for targets named Audio

# Build rule for target.
Audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Audio
.PHONY : Audio

# fast build rule for target.
Audio/fast:
	$(MAKE) $(MAKESILENT) -f src/Audio/CMakeFiles/Audio.dir/build.make src/Audio/CMakeFiles/Audio.dir/build
.PHONY : Audio/fast

#=============================================================================
# Target rules for targets named Audio_autogen

# Build rule for target.
Audio_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Audio_autogen
.PHONY : Audio_autogen

# fast build rule for target.
Audio_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Audio/CMakeFiles/Audio_autogen.dir/build.make src/Audio/CMakeFiles/Audio_autogen.dir/build
.PHONY : Audio_autogen/fast

#=============================================================================
# Target rules for targets named AutoPilotPlugins

# Build rule for target.
AutoPilotPlugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AutoPilotPlugins
.PHONY : AutoPilotPlugins

# fast build rule for target.
AutoPilotPlugins/fast:
	$(MAKE) $(MAKESILENT) -f src/AutoPilotPlugins/CMakeFiles/AutoPilotPlugins.dir/build.make src/AutoPilotPlugins/CMakeFiles/AutoPilotPlugins.dir/build
.PHONY : AutoPilotPlugins/fast

#=============================================================================
# Target rules for targets named AutoPilotPlugins_autogen

# Build rule for target.
AutoPilotPlugins_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AutoPilotPlugins_autogen
.PHONY : AutoPilotPlugins_autogen

# fast build rule for target.
AutoPilotPlugins_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/AutoPilotPlugins/CMakeFiles/AutoPilotPlugins_autogen.dir/build.make src/AutoPilotPlugins/CMakeFiles/AutoPilotPlugins_autogen.dir/build
.PHONY : AutoPilotPlugins_autogen/fast

#=============================================================================
# Target rules for targets named APMAutoPilotPluginQml

# Build rule for target.
APMAutoPilotPluginQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 APMAutoPilotPluginQml
.PHONY : APMAutoPilotPluginQml

# fast build rule for target.
APMAutoPilotPluginQml/fast:
	$(MAKE) $(MAKESILENT) -f src/AutoPilotPlugins/APM/CMakeFiles/APMAutoPilotPluginQml.dir/build.make src/AutoPilotPlugins/APM/CMakeFiles/APMAutoPilotPluginQml.dir/build
.PHONY : APMAutoPilotPluginQml/fast

#=============================================================================
# Target rules for targets named CommonAutoPilotPluginQml

# Build rule for target.
CommonAutoPilotPluginQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CommonAutoPilotPluginQml
.PHONY : CommonAutoPilotPluginQml

# fast build rule for target.
CommonAutoPilotPluginQml/fast:
	$(MAKE) $(MAKESILENT) -f src/AutoPilotPlugins/Common/CMakeFiles/CommonAutoPilotPluginQml.dir/build.make src/AutoPilotPlugins/Common/CMakeFiles/CommonAutoPilotPluginQml.dir/build
.PHONY : CommonAutoPilotPluginQml/fast

#=============================================================================
# Target rules for targets named PX4AutoPilotPluginQml

# Build rule for target.
PX4AutoPilotPluginQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PX4AutoPilotPluginQml
.PHONY : PX4AutoPilotPluginQml

# fast build rule for target.
PX4AutoPilotPluginQml/fast:
	$(MAKE) $(MAKESILENT) -f src/AutoPilotPlugins/PX4/CMakeFiles/PX4AutoPilotPluginQml.dir/build.make src/AutoPilotPlugins/PX4/CMakeFiles/PX4AutoPilotPluginQml.dir/build
.PHONY : PX4AutoPilotPluginQml/fast

#=============================================================================
# Target rules for targets named Camera

# Build rule for target.
Camera: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Camera
.PHONY : Camera

# fast build rule for target.
Camera/fast:
	$(MAKE) $(MAKESILENT) -f src/Camera/CMakeFiles/Camera.dir/build.make src/Camera/CMakeFiles/Camera.dir/build
.PHONY : Camera/fast

#=============================================================================
# Target rules for targets named Camera_autogen

# Build rule for target.
Camera_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Camera_autogen
.PHONY : Camera_autogen

# fast build rule for target.
Camera_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Camera/CMakeFiles/Camera_autogen.dir/build.make src/Camera/CMakeFiles/Camera_autogen.dir/build
.PHONY : Camera_autogen/fast

#=============================================================================
# Target rules for targets named comm

# Build rule for target.
comm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 comm
.PHONY : comm

# fast build rule for target.
comm/fast:
	$(MAKE) $(MAKESILENT) -f src/comm/CMakeFiles/comm.dir/build.make src/comm/CMakeFiles/comm.dir/build
.PHONY : comm/fast

#=============================================================================
# Target rules for targets named comm_autogen

# Build rule for target.
comm_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 comm_autogen
.PHONY : comm_autogen

# fast build rule for target.
comm_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/comm/CMakeFiles/comm_autogen.dir/build.make src/comm/CMakeFiles/comm_autogen.dir/build
.PHONY : comm_autogen/fast

#=============================================================================
# Target rules for targets named compression

# Build rule for target.
compression: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compression
.PHONY : compression

# fast build rule for target.
compression/fast:
	$(MAKE) $(MAKESILENT) -f src/Compression/CMakeFiles/compression.dir/build.make src/Compression/CMakeFiles/compression.dir/build
.PHONY : compression/fast

#=============================================================================
# Target rules for targets named compression_autogen

# Build rule for target.
compression_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compression_autogen
.PHONY : compression_autogen

# fast build rule for target.
compression_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Compression/CMakeFiles/compression_autogen.dir/build.make src/Compression/CMakeFiles/compression_autogen.dir/build
.PHONY : compression_autogen/fast

#=============================================================================
# Target rules for targets named FactSystem

# Build rule for target.
FactSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FactSystem
.PHONY : FactSystem

# fast build rule for target.
FactSystem/fast:
	$(MAKE) $(MAKESILENT) -f src/FactSystem/CMakeFiles/FactSystem.dir/build.make src/FactSystem/CMakeFiles/FactSystem.dir/build
.PHONY : FactSystem/fast

#=============================================================================
# Target rules for targets named FactSystem_autogen

# Build rule for target.
FactSystem_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FactSystem_autogen
.PHONY : FactSystem_autogen

# fast build rule for target.
FactSystem_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/FactSystem/CMakeFiles/FactSystem_autogen.dir/build.make src/FactSystem/CMakeFiles/FactSystem_autogen.dir/build
.PHONY : FactSystem_autogen/fast

#=============================================================================
# Target rules for targets named FactControlsQml

# Build rule for target.
FactControlsQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FactControlsQml
.PHONY : FactControlsQml

# fast build rule for target.
FactControlsQml/fast:
	$(MAKE) $(MAKESILENT) -f src/FactSystem/FactControls/CMakeFiles/FactControlsQml.dir/build.make src/FactSystem/FactControls/CMakeFiles/FactControlsQml.dir/build
.PHONY : FactControlsQml/fast

#=============================================================================
# Target rules for targets named FactControls

# Build rule for target.
FactControls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FactControls
.PHONY : FactControls

# fast build rule for target.
FactControls/fast:
	$(MAKE) $(MAKESILENT) -f src/FactSystem/FactControls/CMakeFiles/FactControls.dir/build.make src/FactSystem/FactControls/CMakeFiles/FactControls.dir/build
.PHONY : FactControls/fast

#=============================================================================
# Target rules for targets named FactControls_autogen

# Build rule for target.
FactControls_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FactControls_autogen
.PHONY : FactControls_autogen

# fast build rule for target.
FactControls_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/FactSystem/FactControls/CMakeFiles/FactControls_autogen.dir/build.make src/FactSystem/FactControls/CMakeFiles/FactControls_autogen.dir/build
.PHONY : FactControls_autogen/fast

#=============================================================================
# Target rules for targets named FirmwarePlugin

# Build rule for target.
FirmwarePlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FirmwarePlugin
.PHONY : FirmwarePlugin

# fast build rule for target.
FirmwarePlugin/fast:
	$(MAKE) $(MAKESILENT) -f src/FirmwarePlugin/CMakeFiles/FirmwarePlugin.dir/build.make src/FirmwarePlugin/CMakeFiles/FirmwarePlugin.dir/build
.PHONY : FirmwarePlugin/fast

#=============================================================================
# Target rules for targets named FirmwarePlugin_autogen

# Build rule for target.
FirmwarePlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FirmwarePlugin_autogen
.PHONY : FirmwarePlugin_autogen

# fast build rule for target.
FirmwarePlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/FirmwarePlugin/CMakeFiles/FirmwarePlugin_autogen.dir/build.make src/FirmwarePlugin/CMakeFiles/FirmwarePlugin_autogen.dir/build
.PHONY : FirmwarePlugin_autogen/fast

#=============================================================================
# Target rules for targets named APMFirmwarePluginQml

# Build rule for target.
APMFirmwarePluginQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 APMFirmwarePluginQml
.PHONY : APMFirmwarePluginQml

# fast build rule for target.
APMFirmwarePluginQml/fast:
	$(MAKE) $(MAKESILENT) -f src/FirmwarePlugin/APM/CMakeFiles/APMFirmwarePluginQml.dir/build.make src/FirmwarePlugin/APM/CMakeFiles/APMFirmwarePluginQml.dir/build
.PHONY : APMFirmwarePluginQml/fast

#=============================================================================
# Target rules for targets named FligthDisplayQml

# Build rule for target.
FligthDisplayQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FligthDisplayQml
.PHONY : FligthDisplayQml

# fast build rule for target.
FligthDisplayQml/fast:
	$(MAKE) $(MAKESILENT) -f src/FlightDisplay/CMakeFiles/FligthDisplayQml.dir/build.make src/FlightDisplay/CMakeFiles/FligthDisplayQml.dir/build
.PHONY : FligthDisplayQml/fast

#=============================================================================
# Target rules for targets named FligthMapQml

# Build rule for target.
FligthMapQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FligthMapQml
.PHONY : FligthMapQml

# fast build rule for target.
FligthMapQml/fast:
	$(MAKE) $(MAKESILENT) -f src/FlightMap/CMakeFiles/FligthMapQml.dir/build.make src/FlightMap/CMakeFiles/FligthMapQml.dir/build
.PHONY : FligthMapQml/fast

#=============================================================================
# Target rules for targets named FlightMap

# Build rule for target.
FlightMap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FlightMap
.PHONY : FlightMap

# fast build rule for target.
FlightMap/fast:
	$(MAKE) $(MAKESILENT) -f src/FlightMap/CMakeFiles/FlightMap.dir/build.make src/FlightMap/CMakeFiles/FlightMap.dir/build
.PHONY : FlightMap/fast

#=============================================================================
# Target rules for targets named FlightMap_autogen

# Build rule for target.
FlightMap_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FlightMap_autogen
.PHONY : FlightMap_autogen

# fast build rule for target.
FlightMap_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/FlightMap/CMakeFiles/FlightMap_autogen.dir/build.make src/FlightMap/CMakeFiles/FlightMap_autogen.dir/build
.PHONY : FlightMap_autogen/fast

#=============================================================================
# Target rules for targets named FligthMapItemsQml

# Build rule for target.
FligthMapItemsQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FligthMapItemsQml
.PHONY : FligthMapItemsQml

# fast build rule for target.
FligthMapItemsQml/fast:
	$(MAKE) $(MAKESILENT) -f src/FlightMap/MapItems/CMakeFiles/FligthMapItemsQml.dir/build.make src/FlightMap/MapItems/CMakeFiles/FligthMapItemsQml.dir/build
.PHONY : FligthMapItemsQml/fast

#=============================================================================
# Target rules for targets named FligthMapWidgetsQml

# Build rule for target.
FligthMapWidgetsQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FligthMapWidgetsQml
.PHONY : FligthMapWidgetsQml

# fast build rule for target.
FligthMapWidgetsQml/fast:
	$(MAKE) $(MAKESILENT) -f src/FlightMap/Widgets/CMakeFiles/FligthMapWidgetsQml.dir/build.make src/FlightMap/Widgets/CMakeFiles/FligthMapWidgetsQml.dir/build
.PHONY : FligthMapWidgetsQml/fast

#=============================================================================
# Target rules for targets named FollowMe

# Build rule for target.
FollowMe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FollowMe
.PHONY : FollowMe

# fast build rule for target.
FollowMe/fast:
	$(MAKE) $(MAKESILENT) -f src/FollowMe/CMakeFiles/FollowMe.dir/build.make src/FollowMe/CMakeFiles/FollowMe.dir/build
.PHONY : FollowMe/fast

#=============================================================================
# Target rules for targets named FollowMe_autogen

# Build rule for target.
FollowMe_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FollowMe_autogen
.PHONY : FollowMe_autogen

# fast build rule for target.
FollowMe_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/FollowMe/CMakeFiles/FollowMe_autogen.dir/build.make src/FollowMe/CMakeFiles/FollowMe_autogen.dir/build
.PHONY : FollowMe_autogen/fast

#=============================================================================
# Target rules for targets named Geo

# Build rule for target.
Geo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Geo
.PHONY : Geo

# fast build rule for target.
Geo/fast:
	$(MAKE) $(MAKESILENT) -f src/Geo/CMakeFiles/Geo.dir/build.make src/Geo/CMakeFiles/Geo.dir/build
.PHONY : Geo/fast

#=============================================================================
# Target rules for targets named Geo_autogen

# Build rule for target.
Geo_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Geo_autogen
.PHONY : Geo_autogen

# fast build rule for target.
Geo_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Geo/CMakeFiles/Geo_autogen.dir/build.make src/Geo/CMakeFiles/Geo_autogen.dir/build
.PHONY : Geo_autogen/fast

#=============================================================================
# Target rules for targets named gps

# Build rule for target.
gps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gps
.PHONY : gps

# fast build rule for target.
gps/fast:
	$(MAKE) $(MAKESILENT) -f src/GPS/CMakeFiles/gps.dir/build.make src/GPS/CMakeFiles/gps.dir/build
.PHONY : gps/fast

#=============================================================================
# Target rules for targets named gps_autogen

# Build rule for target.
gps_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gps_autogen
.PHONY : gps_autogen

# fast build rule for target.
gps_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/GPS/CMakeFiles/gps_autogen.dir/build.make src/GPS/CMakeFiles/gps_autogen.dir/build
.PHONY : gps_autogen/fast

#=============================================================================
# Target rules for targets named Joystick

# Build rule for target.
Joystick: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Joystick
.PHONY : Joystick

# fast build rule for target.
Joystick/fast:
	$(MAKE) $(MAKESILENT) -f src/Joystick/CMakeFiles/Joystick.dir/build.make src/Joystick/CMakeFiles/Joystick.dir/build
.PHONY : Joystick/fast

#=============================================================================
# Target rules for targets named Joystick_autogen

# Build rule for target.
Joystick_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Joystick_autogen
.PHONY : Joystick_autogen

# fast build rule for target.
Joystick_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Joystick/CMakeFiles/Joystick_autogen.dir/build.make src/Joystick/CMakeFiles/Joystick_autogen.dir/build
.PHONY : Joystick_autogen/fast

#=============================================================================
# Target rules for targets named MisionManagerQml

# Build rule for target.
MisionManagerQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MisionManagerQml
.PHONY : MisionManagerQml

# fast build rule for target.
MisionManagerQml/fast:
	$(MAKE) $(MAKESILENT) -f src/MissionManager/CMakeFiles/MisionManagerQml.dir/build.make src/MissionManager/CMakeFiles/MisionManagerQml.dir/build
.PHONY : MisionManagerQml/fast

#=============================================================================
# Target rules for targets named MissionManager

# Build rule for target.
MissionManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MissionManager
.PHONY : MissionManager

# fast build rule for target.
MissionManager/fast:
	$(MAKE) $(MAKESILENT) -f src/MissionManager/CMakeFiles/MissionManager.dir/build.make src/MissionManager/CMakeFiles/MissionManager.dir/build
.PHONY : MissionManager/fast

#=============================================================================
# Target rules for targets named MissionManager_autogen

# Build rule for target.
MissionManager_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MissionManager_autogen
.PHONY : MissionManager_autogen

# fast build rule for target.
MissionManager_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/MissionManager/CMakeFiles/MissionManager_autogen.dir/build.make src/MissionManager/CMakeFiles/MissionManager_autogen.dir/build
.PHONY : MissionManager_autogen/fast

#=============================================================================
# Target rules for targets named PlanViewQml

# Build rule for target.
PlanViewQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PlanViewQml
.PHONY : PlanViewQml

# fast build rule for target.
PlanViewQml/fast:
	$(MAKE) $(MAKESILENT) -f src/PlanView/CMakeFiles/PlanViewQml.dir/build.make src/PlanView/CMakeFiles/PlanViewQml.dir/build
.PHONY : PlanViewQml/fast

#=============================================================================
# Target rules for targets named PositionManager

# Build rule for target.
PositionManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PositionManager
.PHONY : PositionManager

# fast build rule for target.
PositionManager/fast:
	$(MAKE) $(MAKESILENT) -f src/PositionManager/CMakeFiles/PositionManager.dir/build.make src/PositionManager/CMakeFiles/PositionManager.dir/build
.PHONY : PositionManager/fast

#=============================================================================
# Target rules for targets named PositionManager_autogen

# Build rule for target.
PositionManager_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PositionManager_autogen
.PHONY : PositionManager_autogen

# fast build rule for target.
PositionManager_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/PositionManager/CMakeFiles/PositionManager_autogen.dir/build.make src/PositionManager/CMakeFiles/PositionManager_autogen.dir/build
.PHONY : PositionManager_autogen/fast

#=============================================================================
# Target rules for targets named QmlControlsQml

# Build rule for target.
QmlControlsQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QmlControlsQml
.PHONY : QmlControlsQml

# fast build rule for target.
QmlControlsQml/fast:
	$(MAKE) $(MAKESILENT) -f src/QmlControls/CMakeFiles/QmlControlsQml.dir/build.make src/QmlControls/CMakeFiles/QmlControlsQml.dir/build
.PHONY : QmlControlsQml/fast

#=============================================================================
# Target rules for targets named QmlControls

# Build rule for target.
QmlControls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QmlControls
.PHONY : QmlControls

# fast build rule for target.
QmlControls/fast:
	$(MAKE) $(MAKESILENT) -f src/QmlControls/CMakeFiles/QmlControls.dir/build.make src/QmlControls/CMakeFiles/QmlControls.dir/build
.PHONY : QmlControls/fast

#=============================================================================
# Target rules for targets named QmlControls_autogen

# Build rule for target.
QmlControls_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QmlControls_autogen
.PHONY : QmlControls_autogen

# fast build rule for target.
QmlControls_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/QmlControls/CMakeFiles/QmlControls_autogen.dir/build.make src/QmlControls/CMakeFiles/QmlControls_autogen.dir/build
.PHONY : QmlControls_autogen/fast

#=============================================================================
# Target rules for targets named QtLocationPlugin

# Build rule for target.
QtLocationPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtLocationPlugin
.PHONY : QtLocationPlugin

# fast build rule for target.
QtLocationPlugin/fast:
	$(MAKE) $(MAKESILENT) -f src/QtLocationPlugin/CMakeFiles/QtLocationPlugin.dir/build.make src/QtLocationPlugin/CMakeFiles/QtLocationPlugin.dir/build
.PHONY : QtLocationPlugin/fast

#=============================================================================
# Target rules for targets named QtLocationPlugin_autogen

# Build rule for target.
QtLocationPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtLocationPlugin_autogen
.PHONY : QtLocationPlugin_autogen

# fast build rule for target.
QtLocationPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/QtLocationPlugin/CMakeFiles/QtLocationPlugin_autogen.dir/build.make src/QtLocationPlugin/CMakeFiles/QtLocationPlugin_autogen.dir/build
.PHONY : QtLocationPlugin_autogen/fast

#=============================================================================
# Target rules for targets named Settings

# Build rule for target.
Settings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Settings
.PHONY : Settings

# fast build rule for target.
Settings/fast:
	$(MAKE) $(MAKESILENT) -f src/Settings/CMakeFiles/Settings.dir/build.make src/Settings/CMakeFiles/Settings.dir/build
.PHONY : Settings/fast

#=============================================================================
# Target rules for targets named Settings_autogen

# Build rule for target.
Settings_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Settings_autogen
.PHONY : Settings_autogen

# fast build rule for target.
Settings_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Settings/CMakeFiles/Settings_autogen.dir/build.make src/Settings/CMakeFiles/Settings_autogen.dir/build
.PHONY : Settings_autogen/fast

#=============================================================================
# Target rules for targets named Terrain

# Build rule for target.
Terrain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Terrain
.PHONY : Terrain

# fast build rule for target.
Terrain/fast:
	$(MAKE) $(MAKESILENT) -f src/Terrain/CMakeFiles/Terrain.dir/build.make src/Terrain/CMakeFiles/Terrain.dir/build
.PHONY : Terrain/fast

#=============================================================================
# Target rules for targets named Terrain_autogen

# Build rule for target.
Terrain_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Terrain_autogen
.PHONY : Terrain_autogen

# fast build rule for target.
Terrain_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Terrain/CMakeFiles/Terrain_autogen.dir/build.make src/Terrain/CMakeFiles/Terrain_autogen.dir/build
.PHONY : Terrain_autogen/fast

#=============================================================================
# Target rules for targets named uas

# Build rule for target.
uas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uas
.PHONY : uas

# fast build rule for target.
uas/fast:
	$(MAKE) $(MAKESILENT) -f src/uas/CMakeFiles/uas.dir/build.make src/uas/CMakeFiles/uas.dir/build
.PHONY : uas/fast

#=============================================================================
# Target rules for targets named uas_autogen

# Build rule for target.
uas_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uas_autogen
.PHONY : uas_autogen

# fast build rule for target.
uas_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/uas/CMakeFiles/uas_autogen.dir/build.make src/uas/CMakeFiles/uas_autogen.dir/build
.PHONY : uas_autogen/fast

#=============================================================================
# Target rules for targets named Vehicle

# Build rule for target.
Vehicle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vehicle
.PHONY : Vehicle

# fast build rule for target.
Vehicle/fast:
	$(MAKE) $(MAKESILENT) -f src/Vehicle/CMakeFiles/Vehicle.dir/build.make src/Vehicle/CMakeFiles/Vehicle.dir/build
.PHONY : Vehicle/fast

#=============================================================================
# Target rules for targets named Vehicle_autogen

# Build rule for target.
Vehicle_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vehicle_autogen
.PHONY : Vehicle_autogen

# fast build rule for target.
Vehicle_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Vehicle/CMakeFiles/Vehicle_autogen.dir/build.make src/Vehicle/CMakeFiles/Vehicle_autogen.dir/build
.PHONY : Vehicle_autogen/fast

#=============================================================================
# Target rules for targets named VehicleSetupQml

# Build rule for target.
VehicleSetupQml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VehicleSetupQml
.PHONY : VehicleSetupQml

# fast build rule for target.
VehicleSetupQml/fast:
	$(MAKE) $(MAKESILENT) -f src/VehicleSetup/CMakeFiles/VehicleSetupQml.dir/build.make src/VehicleSetup/CMakeFiles/VehicleSetupQml.dir/build
.PHONY : VehicleSetupQml/fast

#=============================================================================
# Target rules for targets named VehicleSetup

# Build rule for target.
VehicleSetup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VehicleSetup
.PHONY : VehicleSetup

# fast build rule for target.
VehicleSetup/fast:
	$(MAKE) $(MAKESILENT) -f src/VehicleSetup/CMakeFiles/VehicleSetup.dir/build.make src/VehicleSetup/CMakeFiles/VehicleSetup.dir/build
.PHONY : VehicleSetup/fast

#=============================================================================
# Target rules for targets named VehicleSetup_autogen

# Build rule for target.
VehicleSetup_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VehicleSetup_autogen
.PHONY : VehicleSetup_autogen

# fast build rule for target.
VehicleSetup_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/VehicleSetup/CMakeFiles/VehicleSetup_autogen.dir/build.make src/VehicleSetup/CMakeFiles/VehicleSetup_autogen.dir/build
.PHONY : VehicleSetup_autogen/fast

#=============================================================================
# Target rules for targets named VideoManager

# Build rule for target.
VideoManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VideoManager
.PHONY : VideoManager

# fast build rule for target.
VideoManager/fast:
	$(MAKE) $(MAKESILENT) -f src/VideoManager/CMakeFiles/VideoManager.dir/build.make src/VideoManager/CMakeFiles/VideoManager.dir/build
.PHONY : VideoManager/fast

#=============================================================================
# Target rules for targets named VideoManager_autogen

# Build rule for target.
VideoManager_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VideoManager_autogen
.PHONY : VideoManager_autogen

# fast build rule for target.
VideoManager_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/VideoManager/CMakeFiles/VideoManager_autogen.dir/build.make src/VideoManager/CMakeFiles/VideoManager_autogen.dir/build
.PHONY : VideoManager_autogen/fast

#=============================================================================
# Target rules for targets named VideoReceiver

# Build rule for target.
VideoReceiver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VideoReceiver
.PHONY : VideoReceiver

# fast build rule for target.
VideoReceiver/fast:
	$(MAKE) $(MAKESILENT) -f src/VideoReceiver/CMakeFiles/VideoReceiver.dir/build.make src/VideoReceiver/CMakeFiles/VideoReceiver.dir/build
.PHONY : VideoReceiver/fast

#=============================================================================
# Target rules for targets named VideoReceiver_autogen

# Build rule for target.
VideoReceiver_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VideoReceiver_autogen
.PHONY : VideoReceiver_autogen

# fast build rule for target.
VideoReceiver_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/VideoReceiver/CMakeFiles/VideoReceiver_autogen.dir/build.make src/VideoReceiver/CMakeFiles/VideoReceiver_autogen.dir/build
.PHONY : VideoReceiver_autogen/fast

QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.o: QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.o

.PHONY : QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.o

# target to build an object file
QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.o
.PHONY : QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.o

QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.i: QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.i

.PHONY : QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.i

# target to preprocess a source file
QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.i
.PHONY : QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.i

QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.s: QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.s

.PHONY : QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.s

# target to generate assembly for a file
QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.s
.PHONY : QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.s

QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.o: QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.o

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.o

# target to build an object file
QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.o
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.o

QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.i: QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.i

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.i

# target to preprocess a source file
QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.i
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.i

QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.s: QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.s

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.s

# target to generate assembly for a file
QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.s
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.s

QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.o: QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.o

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.o

# target to build an object file
QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.o
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.o

QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.i: QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.i

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.i

# target to preprocess a source file
QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.i
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.i

QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.s: QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.s

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.s

# target to generate assembly for a file
QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.s
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.s

QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.o: QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.o

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.o

# target to build an object file
QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.o
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.o

QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.i: QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.i

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.i

# target to preprocess a source file
QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.i
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.i

QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.s: QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.s

.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.s

# target to generate assembly for a file
QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.s
.PHONY : QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.s

QGroundControl_autogen/HUTYNDADG6/qrc_airmap.o: QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.o

.PHONY : QGroundControl_autogen/HUTYNDADG6/qrc_airmap.o

# target to build an object file
QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.o
.PHONY : QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.o

QGroundControl_autogen/HUTYNDADG6/qrc_airmap.i: QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.i

.PHONY : QGroundControl_autogen/HUTYNDADG6/qrc_airmap.i

# target to preprocess a source file
QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.i
.PHONY : QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.i

QGroundControl_autogen/HUTYNDADG6/qrc_airmap.s: QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.s

.PHONY : QGroundControl_autogen/HUTYNDADG6/qrc_airmap.s

# target to generate assembly for a file
QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.s
.PHONY : QGroundControl_autogen/HUTYNDADG6/qrc_airmap.cpp.s

QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.o: QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.o

.PHONY : QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.o

# target to build an object file
QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.o
.PHONY : QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.o

QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.i: QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.i

.PHONY : QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.i

# target to preprocess a source file
QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.i
.PHONY : QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.i

QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.s: QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.s

.PHONY : QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.s

# target to generate assembly for a file
QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.s
.PHONY : QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.cpp.s

QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.o: QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.o

.PHONY : QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.o

# target to build an object file
QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.o
.PHONY : QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.o

QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.i: QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.i

.PHONY : QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.i

# target to preprocess a source file
QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.i
.PHONY : QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.i

QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.s: QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.s

.PHONY : QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.s

# target to generate assembly for a file
QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.s
.PHONY : QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.s

QGroundControl_autogen/SCLPBLNWZG/qrc_qml.o: QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.o

.PHONY : QGroundControl_autogen/SCLPBLNWZG/qrc_qml.o

# target to build an object file
QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.o
.PHONY : QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.o

QGroundControl_autogen/SCLPBLNWZG/qrc_qml.i: QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.i

.PHONY : QGroundControl_autogen/SCLPBLNWZG/qrc_qml.i

# target to preprocess a source file
QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.i
.PHONY : QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.i

QGroundControl_autogen/SCLPBLNWZG/qrc_qml.s: QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.s

.PHONY : QGroundControl_autogen/SCLPBLNWZG/qrc_qml.s

# target to generate assembly for a file
QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.s
.PHONY : QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.s

QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.o: QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.o

.PHONY : QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.o

# target to build an object file
QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.o
.PHONY : QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.o

QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.i: QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.i

.PHONY : QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.i

# target to preprocess a source file
QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.i
.PHONY : QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.i

QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.s: QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.s

.PHONY : QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.s

# target to generate assembly for a file
QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.s
.PHONY : QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.s

QGroundControl_autogen/mocs_compilation.o: QGroundControl_autogen/mocs_compilation.cpp.o

.PHONY : QGroundControl_autogen/mocs_compilation.o

# target to build an object file
QGroundControl_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/mocs_compilation.cpp.o
.PHONY : QGroundControl_autogen/mocs_compilation.cpp.o

QGroundControl_autogen/mocs_compilation.i: QGroundControl_autogen/mocs_compilation.cpp.i

.PHONY : QGroundControl_autogen/mocs_compilation.i

# target to preprocess a source file
QGroundControl_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/mocs_compilation.cpp.i
.PHONY : QGroundControl_autogen/mocs_compilation.cpp.i

QGroundControl_autogen/mocs_compilation.s: QGroundControl_autogen/mocs_compilation.cpp.s

.PHONY : QGroundControl_autogen/mocs_compilation.s

# target to generate assembly for a file
QGroundControl_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QGroundControl.dir/build.make CMakeFiles/QGroundControl.dir/QGroundControl_autogen/mocs_compilation.cpp.s
.PHONY : QGroundControl_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ADSB_autogen"
	@echo "... APMAutoPilotPluginQml"
	@echo "... APMFirmwarePluginQml"
	@echo "... Airmap_autogen"
	@echo "... AnalyzeViewQml"
	@echo "... AnalyzeView_autogen"
	@echo "... Audio_autogen"
	@echo "... AutoPilotPlugins_autogen"
	@echo "... Camera_autogen"
	@echo "... CommonAutoPilotPluginQml"
	@echo "... FactControlsQml"
	@echo "... FactControls_autogen"
	@echo "... FactSystem_autogen"
	@echo "... FirmwarePlugin_autogen"
	@echo "... FlightMap_autogen"
	@echo "... FligthDisplayQml"
	@echo "... FligthMapItemsQml"
	@echo "... FligthMapQml"
	@echo "... FligthMapWidgetsQml"
	@echo "... FollowMe_autogen"
	@echo "... Geo_autogen"
	@echo "... Joystick_autogen"
	@echo "... MisionManagerQml"
	@echo "... MissionManager_autogen"
	@echo "... PX4AutoPilotPluginQml"
	@echo "... PlanViewQml"
	@echo "... PositionManager_autogen"
	@echo "... QGroundControl_autogen"
	@echo "... QmlControlsQml"
	@echo "... QmlControls_autogen"
	@echo "... QtLocationPlugin_autogen"
	@echo "... Settings_autogen"
	@echo "... Terrain_autogen"
	@echo "... UiPreferencesQml"
	@echo "... UiToolbarQml"
	@echo "... VehicleSetupQml"
	@echo "... VehicleSetup_autogen"
	@echo "... Vehicle_autogen"
	@echo "... VideoManager_autogen"
	@echo "... VideoReceiver_autogen"
	@echo "... api_autogen"
	@echo "... comm_autogen"
	@echo "... compression_autogen"
	@echo "... dbfadd_autogen"
	@echo "... dbfcreate_autogen"
	@echo "... dbfdump_autogen"
	@echo "... gps_autogen"
	@echo "... libevents_generated_autogen"
	@echo "... libevents_parser_autogen"
	@echo "... qgc_autogen"
	@echo "... qmlglsink_autogen"
	@echo "... shp_autogen"
	@echo "... shpadd_autogen"
	@echo "... shpcreate_autogen"
	@echo "... shpdump_autogen"
	@echo "... shprewind_autogen"
	@echo "... shptreedump_autogen"
	@echo "... uas_autogen"
	@echo "... uiQml"
	@echo "... ui_autogen"
	@echo "... ADSB"
	@echo "... Airmap"
	@echo "... AnalyzeView"
	@echo "... Audio"
	@echo "... AutoPilotPlugins"
	@echo "... Camera"
	@echo "... FactControls"
	@echo "... FactSystem"
	@echo "... FirmwarePlugin"
	@echo "... FlightMap"
	@echo "... FollowMe"
	@echo "... Geo"
	@echo "... Joystick"
	@echo "... MissionManager"
	@echo "... PositionManager"
	@echo "... QGroundControl"
	@echo "... QmlControls"
	@echo "... QtLocationPlugin"
	@echo "... Settings"
	@echo "... Terrain"
	@echo "... Vehicle"
	@echo "... VehicleSetup"
	@echo "... VideoManager"
	@echo "... VideoReceiver"
	@echo "... api"
	@echo "... comm"
	@echo "... compression"
	@echo "... dbfadd"
	@echo "... dbfcreate"
	@echo "... dbfdump"
	@echo "... gps"
	@echo "... libevents_generated"
	@echo "... libevents_parser"
	@echo "... qgc"
	@echo "... qmlglsink"
	@echo "... shp"
	@echo "... shpadd"
	@echo "... shpcreate"
	@echo "... shpdump"
	@echo "... shprewind"
	@echo "... shptreedump"
	@echo "... uas"
	@echo "... ui"
	@echo "... QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.o"
	@echo "... QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.i"
	@echo "... QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.s"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.o"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.i"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.s"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.o"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.i"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.s"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.o"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.i"
	@echo "... QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.s"
	@echo "... QGroundControl_autogen/HUTYNDADG6/qrc_airmap.o"
	@echo "... QGroundControl_autogen/HUTYNDADG6/qrc_airmap.i"
	@echo "... QGroundControl_autogen/HUTYNDADG6/qrc_airmap.s"
	@echo "... QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.o"
	@echo "... QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.i"
	@echo "... QGroundControl_autogen/K2NRVMZOSX/qrc_airmap_dummy.s"
	@echo "... QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.o"
	@echo "... QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.i"
	@echo "... QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.s"
	@echo "... QGroundControl_autogen/SCLPBLNWZG/qrc_qml.o"
	@echo "... QGroundControl_autogen/SCLPBLNWZG/qrc_qml.i"
	@echo "... QGroundControl_autogen/SCLPBLNWZG/qrc_qml.s"
	@echo "... QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.o"
	@echo "... QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.i"
	@echo "... QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.s"
	@echo "... QGroundControl_autogen/mocs_compilation.o"
	@echo "... QGroundControl_autogen/mocs_compilation.i"
	@echo "... QGroundControl_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

